### ISSUE TITLE
TCP connection to master not closed  on dispose

### ISSUE THREAD

**Issue by mcroissant** [NModbus/NModbus#14] opened 2018-01-24 16:01 UTC
Hello,

I'm currently testing the library for modbus communication in a .Net Core app, however it appears that after disposal of TCPClient the connection to the master is not closed, at least that's what my simulator is telling me (it was closing with an other library : libmodbus C++).

Any advise on how I could get the connection to close properly ? any hint on where to look for, I would'nt be against providing PR.

**Comment by rquackenbush** [comment] 2018-03-06 17:59
Apologies for the (very long) delay getting back to you. Unfortunately, I don't do any Modbus over TCP in my work, so I don't have any experience in this area. I would definitely appreciate a PR!

**Comment by Fuchks** [comment] 2018-06-06 10:05
As NModbus simply uses an established connection over TcpClient and does not handle opening or closing the connection, I suggest that the problem is outside the scope of NModbus.

**Closed** 2018-09-11 15:49 UTC
